# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NovaGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, NOVA):
        NOVA.setObjectName("Main")
        NOVA.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(NOVA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.label.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/GUI/UI-data visualize project.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("NOVAGUI")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 420, 90, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 500, 90, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        NOVA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NOVA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 18))
        self.menubar.setObjectName("menubar")
        NOVA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NOVA)
        self.statusbar.setObjectName("statusbar")
        NOVA.setStatusBar(self.statusbar)

        self.retranslateUi(NOVA)
        QtCore.QMetaObject.connectSlotsByName(NOVA)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.pushButton_2.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NOVA = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(NOVA)
    NOVA.show()
    sys.exit(app.exec_())
